package eaf;

public class eafmain {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		System.out.println("\t\t\t\t\t\t\t\tDE LA SALLE-COLLEGE OF SAINT BENILDE\t\t\t\t\t  000011550378"
				+ "\n\t\t\t\t\t\t\t\t      STUDENT ENROLLMENT RECORD" 
				+ "\n\t\tEAF 2016201-388645   Second TRIM 2016 - 2017   DATE 12/14/2016   STUD. ADJ. NO. A162008171350518"
				+ "\n\t\t\t NAME  PASCUAL, ERNEST EUGENE SUGANOB                                                          GRADUATING?  NO"
				+"\n\t\t\t STUDENT NO 000011550378                                                         STUDENT TYPE  Old Student"
				+ "\n\t\t\t DEGREE BS-IS                                            COLLEGE SMIT                              YEAR 2"
				+ "\n\tAttention transferees, foreigners, & ID 101 and below, please inquire on your community service program at the CSA at (02)2305100 loc.1514/1515"
				+"\n\t\t\t\tNO.     COURSE CODE     SEC    UNITS    DAYS    HOURS      BLDG      FACULTY"
				+"\n\t\t\t\t1         TRIGONO      TI101    3.0      MW   08:00-09:30  M405"
				+"\n\t\t\t\t2	  TECWRIT      HFH14    3.0      MW   09:40-11:10  M305"
				+"\n\t\t\t\t					 H    14:40-16:10  M305"
				+"\n\t\t\t\t3	  PROGAP1      TI003    3.0      MW   18:00-19:30  DCL3"
				+"\n\t\t\t\t4	  BUFINMA      TI001    3.0      MW   19:45-21:15  M304"
				+"\n\t\t\t\t5	  IS-EBIZ      TI001    3.0      S    08:00-11:00  I807"
				+"\n\t\t\t\t6	  PRJ-MGT      TI001    3.0      S    11:20-14:20  M402" 
				+"\n\n\n\n\n\n\n\n"
				+"\t\tRecord updated. Previous EAF invalid. Print updated EAF for Finance Department (FD) reference."
				+"\n\n\t\t*Enrollment is valid only upon acceptance of payment by DLS-CSB"
				+"\n\t\tDeadline of payment w/o surcharge : 04 JAN 2017"
				+"\n\t\tDeadline of payment with surcharge : 18 JAN 2017     (No enrollment will be accepted beyond this date.)"
				+"\n\n\t\t\t\tAcad 18.0"
				+"\n\t\tTOTAL UNITS   Non-Acad 0.0 \t\t\t\t\t\tASSESSED AMT.  62,751.50"
				+"\n\n\n ________________________________________________________________________________________________________________________________________________________"
				+ "\n\t\t\t\t\t\t\t\tDE LA SALLE-COLLEGE OF SAINT BENILDE\t\t\t\t\t  000011550378"
				+ "\n\t\t\t\t\t\t\t\t      STUDENT ENROLLMENT RECORD" 
				+ "\n\t\tEAF 2016201-388645   Second TRIM 2016 - 2017   DATE 12/14/2016   STUD. ADJ. NO. A162008171350518"
				+ "\n\t\t\t NAME  PASCUAL, ERNEST EUGENE SUGANOB                                                          GRADUATING?  NO"
				+"\n\t\t\t STUDENT NO 000011550378                                                         STUDENT TYPE  Old Student"
				+ "\n\t\t\t DEGREE BS-IS                                            COLLEGE SMIT                              YEAR 2"
				+"\n\t\t\t ADDRESS VICTORIA DE MANILA, TAFT AVENUE CORNER MALVAR STREET\t\t\t\tTEL"
				+"\n\t\t\t\t MALATE MANILA 1004\n"
				+"\n\t\t\t\tTYPES OF FEES \t\tASSESSMENT"
				+"\n\t\t\t\tTUITION FEE \t\t50,719.50"
				+"\n\t\t\t\tLABORATORY FEES \t4,778.00"
				+"\n\t\t\t\tMISCELLANEOUS FEES \t7,026.00"
				+"\n\t\t\t\tSPECIAL FEES \t\t228.00"
				+"\n\t\t\t\tADJUSTMENT FEE \t\t30.00"
				+"\n\n\n\t\t\tASSESSED AMT. 62,751.50 \t\t\t\tOTHER FEES 30.00"
				+"\n\t\t\tTOTAL AMT. DUE 62,781.50"
				+"\n\t\t\tTERMS OF PAYMENT PVA \t\t\t\t\tTRIMESTRAL \t\t\t\t\t2 - INST."
				+"\n\t\t\t\t( ) CASH \t\t\t\t\t( ) INSTALLMENT"
				+"\n\t\tIF SECOND ASSESSMENT: AMOUNT PREVIOUSLY PAID 0.00"
				+"\n\t\tEXCESS FR. PREV. AMOUNT PAID : 0.00 BALANCE 62,781.50 (AMOUNT TO BE PAID)"
				+"\n\n\n __________________________________________"
				+ "______________________________________________________________________________________________________________"
				+"\n\t\tDe La Salle-College of Saint Benilde\t\t\t\t\t\tDate Printed: 12/14/2016 2:04:29 AM"
				+"\n\t\tBreakdown of Tuition and Fees\t\t\t\t\t\t\tPrinted By : 000011550378"
				+"\n\t\tSecond Trimester, SY 2016-2017"
				+"\n\t\tStudent No. : 000011550378\t\t\t\t\t\t\tSchool : SMIT"
				+"\n\t\tStudent Name : PASCUAL, ERNEST EUGENE SUGANOB\t\t\t\t\tDegree : BS-IS"
				+"\n\t\t\t\t\t\t\t\t\t\t\t\tTrack : NOTRK"
				+"\n\n\n\t\tAssessment\t\t\t\t\t\t\t\t\tAmount"
				+"\n\t\tTUITION FEE \t\t\t\t\t\t\t\t\t\t\t50,719.50"
				+"\n\t\t\tTUITION FEE\t\t\t\t\t\t\t\t50,719.50"
				+"\n\t\tLABORATORY FEES\t\t\t\t\t\t\t\t\t\t\t4,778.00"
				+"\n\t\t\tCOMPUTER LAB FEE\t\t\t\t\t\t\t4,778.00"
				+"\n\t\tMISCELLANEOUS FEES\t\t\t\t\t\t\t\t\t\t7,026.00"
				+"\n\t\t\tACADEMIC ADVISING FEE\t\t\t\t\t\t\t669.00"
				+"\n\t\t\tATHLETICS FEE\t\t\t\t\t\t\t\t402.00"
				+"\n\t\t\tDEVELOPMENT FEE\t\t\t\t\t\t\t\t1,342.00"
				+"\n\t\t\tGUIDANCE FEE\t\t\t\t\t\t\t\t555.00"
				+"\n\t\t\tINTERNET FEE\t\t\t\t\t\t\t\t537.00"
				+"\n\t\t\tLIBRARY FEE\t\t\t\t\t\t\t\t1,976.00"
				+"\n\t\t\tMEDICAL/DENTAL FEE\t\t\t\t\t\t\t555.00"
				+"\n\t\t\tPUBLICATIONS FEE\t\t\t\t\t\t\t97.00"
				+"\n\t\t\tSTUDENT SERVICES/ACTIVITIES FEE\t\t\t\t\t\t472.00"
				+"\n\t\t\tTRIMESTRAL REGISTRATION FEE\t\t\t\t\t\t421.00"
				+"\n\t\tSPECIAL FEES\t\t\t\t\t\t\t\t\t\t\t228.00"
				+"\n\t\t\tALUMNI FEE\t\t\t\t\t\t\t\t150.00"
				+"\n\t\t\tINSURANCE\t\t\t\t\t\t\t\t78.00"
				+"\n\t\tASSESSED AMOUNT\t\t\t\t\t\t\t\t\t\t\t62,751.50"
				+"\n\t\tOTHER DUES\t\t\t\t\t\t\t\t\t\t\t30.00"
				+"\n\t\t\tADJUSTMENT FEE\t\t\t\t\t\t\t\t30.00"
				);
	}

}
